"""`compare()` must not have moved a digit. Every §1-§54 number came out of it.

WHY A GOLDEN FILE AND NOT §23's OWN INTERVALS. §23 published
Bonferroni K=4 CI [-$16.50, +$64.72] and uncorrected [-$10.65, +$52.94], and
those cannot be recomputed: `memory/backtest_trials.jsonl` stores per-variant
SUMMARIES, not per-trade P&L, so the raw arms are gone. Pinning numbers that
cannot be regenerated would be a check that cannot fail.

What CAN be frozen is the function, on corpora built deterministically from
fixed seeds. `tests/data/significance_golden.json` was generated by running the
UNMODIFIED module — before `_IntervalVerdict` was extracted and before
`compare_paired` existed — and committed in the same PR. If §55 moved anything
in the incumbent path, this goes red.

The corpus deliberately spans all three verdict branches. The first version did
not: every case landed INCONCLUSIVE, which is realistic at swing-trade sample
sizes and useless as a guard, because a mutation to the SIGNIFICANT or
SIGNIFICANTLY WORSE branch would have survived it untouched.
"""
from __future__ import annotations

import json
import random
import sys
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))
import significance as sig  # noqa: E402

GOLDEN = ROOT / "tests" / "data" / "significance_golden.json"


def corpus(seed, n, mean, spread, tail=0.08):
    """Must stay byte-identical to the generator in the PR that froze the file.
    Changing it silently would rebase the guard onto different data."""
    rng = random.Random(seed)
    out = []
    for _ in range(n):
        out.append(rng.gauss(mean, spread * 6) if rng.random() < tail
                   else rng.gauss(mean, spread))
    return [round(x, 6) for x in out]


def cases():
    return sorted(json.loads(GOLDEN.read_text()).items())


@pytest.mark.parametrize("label,want", cases())
def test_compare_reproduces_the_frozen_interval(label, want):
    got = sig.compare(corpus(*want["baseline"]), corpus(*want["candidate"]),
                      n_comparisons=want["k"], resamples=want["resamples"])
    # repr, not round(): the guard is on the float, not on a rendering of it.
    assert repr(got.ci_low) == want["ci_low"], f"{label}: ci_low moved"
    assert repr(got.ci_high) == want["ci_high"], f"{label}: ci_high moved"
    assert repr(got.diff) == want["diff"], f"{label}: diff moved"
    assert repr(got.baseline_mean) == want["baseline_mean"]
    assert repr(got.candidate_mean) == want["candidate_mean"]
    assert repr(got.alpha) == want["alpha"]
    assert got.verdict == want["verdict"]
    assert got.describe() == want["describe"], f"{label}: describe() moved"


def test_the_golden_corpus_exercises_every_verdict_branch():
    """Without this the file could drift back to all-INCONCLUSIVE and nobody
    would notice that two thirds of the verdict logic had stopped being
    guarded."""
    verdicts = {v["verdict"] for _, v in cases()}
    assert verdicts == {"SIGNIFICANT", "SIGNIFICANTLY WORSE", "INCONCLUSIVE"}


def test_the_golden_file_is_not_empty():
    assert len(cases()) >= 9
