"""Generate `research/INDEX.md` — one line per § of the research record.

WHY (Phase 8, 2026-08-06)
-------------------------
`knowledge/backtest_candidates.md` is 5,674 chronological, append-only lines
across 46 sections. To an outsider it is unreadable, and **that is not a reason
to split it**: the chronology is the single strongest piece of evidence in the
repo that nothing was retrofitted. A claim written before its result, in a file
that only ever grows, cannot be quietly reworded after the fact.

So the log is left exactly as it is and gets a table of contents instead.

GENERATED, NEVER HAND-EDITED. A hand-maintained index of a 46-section file is
the divergence-table bug waiting to happen again — on 2026-08-06 that table was
found to be missing four of eighteen entries, three of them open, because
nothing regenerated it. `tests/test_research_index.py` regenerates this file and
fails if the committed copy differs, so it cannot drift.

Run: `.venv/bin/python scripts/gen_research_index.py`
"""
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
SOURCE = ROOT / "knowledge" / "backtest_candidates.md"
OUT = ROOT / "research" / "INDEX.md"

HEADING = re.compile(r"^## (§[\d–—\-]+[a-z]?)\s*[—-]?\s*(.*)$", re.M)

# Verdict words, checked longest-first so "NOT YET RUN" is not read as "RUN"
# and "PRE-REGISTERED, NOT YET RUN" does not score as ADOPTED.
VERDICTS = [
    ("NOT YET RUN", "not yet run"),
    ("PRE-REGISTERED", "pre-registered"),
    ("REJECTED", "rejected"),
    ("ADOPTED", "adopted"),
    ("BLOCKED", "blocked"),
    ("FROZEN", "frozen"),
    ("VALIDATED", "validated"),
    ("REFUTED", "refuted"),
    ("CLOSED", "closed"),
]

CLAIM_TYPES = ["EDGE", "CAPACITY", "METHOD", "DIAGNOSTIC"]


def classify(title: str) -> tuple[str, str]:
    """Return (claim_type, verdict) read off the heading itself.

    Deliberately literal. Inferring a verdict the heading does not state would
    make this index an opinion about the record rather than a view of it.
    """
    upper = title.upper()
    claim = next((c for c in CLAIM_TYPES if c in upper), "—")
    verdict = "—"
    for needle, label in VERDICTS:
        if needle in upper:
            verdict = label
            break
    # A heading naming two outcomes ("ADOPTED for meanrev, REJECTED for tsmom")
    # is genuinely both; say so rather than picking the first.
    if "ADOPTED" in upper and "REJECTED" in upper:
        verdict = "split"
    return claim, verdict


def date_of(title: str) -> str:
    m = re.search(r"(\d{4}-\d{2}-\d{2})", title)
    return m.group(1) if m else "—"


def short(title: str, limit: int = 78) -> str:
    """Strip the date and verdict noise; keep the subject."""
    # Any parenthetical carrying a date — the date has its own column, and the
    # claim type has another, so repeating both in the subject wastes the width
    # that the actual subject needs.
    t = re.sub(r"\([^)]*\d{4}-\d{2}-\d{2}[^)]*\)", "", title)
    t = re.sub(r"\s*[—-]\s*(ADOPTED|REJECTED|PRE-REGISTERED|NOT YET RUN|"
               r"BLOCKED|FROZEN|VALIDATED|REFUTED|NEW STANDING DIAGNOSTIC).*$",
               "", t, flags=re.I)
    t = " ".join(t.split()).strip(" —-,")
    t = t.replace("|", "\\|")
    return (t[:limit - 1] + "…") if len(t) > limit else t


def build() -> str:
    text = SOURCE.read_text()
    rows = []
    for m in HEADING.finditer(text):
        section, title = m.group(1), m.group(2)
        claim, verdict = classify(title)
        rows.append((section, short(title), claim, verdict, date_of(title)))

    lines = [
        "# Research index",
        "",
        "**Generated by `scripts/gen_research_index.py`. Do not edit by hand.**",
        "`tests/test_research_index.py` regenerates this file and fails if the",
        "committed copy differs.",
        "",
        f"One line per section of [`../knowledge/backtest_candidates.md`]"
        f"(../knowledge/backtest_candidates.md) — **{len(rows)} sections, "
        f"{len(SOURCE.read_text().splitlines()):,} lines**.",
        "",
        "That file is chronological and append-only, and it is deliberately NOT",
        "split. The chronology is the evidence that nothing was retrofitted: a",
        "claim written before its result, in a file that only ever grows, cannot",
        "be quietly reworded afterwards. This index is navigation, not a summary,",
        "and the verdict column is read verbatim off each heading rather than",
        "inferred — an index that formed its own opinion of the record would be a",
        "second source of truth.",
        "",
        "| § | subject | claim | verdict | date |",
        "|---|---|---|---|---|",
    ]
    for section, title, claim, verdict, date in rows:
        lines.append(f"| {section} | {title} | {claim} | {verdict} | {date} |")
    lines.append("")
    return "\n".join(lines)


if __name__ == "__main__":
    content = build()
    if "--check" in sys.argv:
        current = OUT.read_text() if OUT.exists() else ""
        if current != content:
            print("research/INDEX.md is STALE — run "
                  "`.venv/bin/python scripts/gen_research_index.py`")
            sys.exit(1)
        print("research/INDEX.md is current")
    else:
        OUT.parent.mkdir(parents=True, exist_ok=True)
        OUT.write_text(content)
        print(f"wrote {OUT.relative_to(ROOT)} "
              f"({len(content.splitlines())} lines)")
